name: deployment

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Execute remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            export PATH=$PATH:/root/.nvm/versions/node/v22.19.0/bin
            cd /root/app/photoserver  # path where your app lives
            git pull origin main
            npm install
            pm2 restart photoserver
